name: bilet_devret
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  image_cropper: ^1.2.3
  image_picker: ^0.6.7+4
  firebase_messaging: ^6.0.16
  extended_image: ^0.9.0
  dartz: ^0.9.0
  characters: ^1.0.0
  flutter_bloc: ^5.0.1
  cached_network_image: ^2.2.0+1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.0
  timeago: ^2.0.26
  google_sign_in: ^4.4.4
  get_it: ^4.0.2
  url_launcher: ^5.2.5
  flushbar: ^1.10.2
  dash_chat: ^1.1.11
  injectable: ^0.3.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  uuid: ^2.0.4
  auto_route: ^0.5.0
  styled_widget: ^0.2.1+2
  cloud_firestore: ^0.13.5
  kt_dart: ^0.7.0+1
  rxdart: ^0.24.0
  flutter_hooks: ^0.9.0
  flutter_datetime_picker: ^1.3.8
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  firebase_storage: ^3.1.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:

  flutter_launcher_icons: ^0.7.5
  auto_route_generator: ^0.5.0
  build_runner: null
  freezed: ^0.10.7
  lint: ^1.1.1
  json_serializable: ^3.3.0
  injectable_generator: ^0.3.5
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: "launcher_icon"
  ios: true

dependency_overrides:
  analyzer: '0.39.14'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  assets:
    - lang/en.json
    - lang/tr.json

    - assets/json/city_town_data_tr.json
    - assets/json/event_categories.json
    - assets/images/app_logo.png
    - assets/images/default_user_icon.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

